#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development: &development_defaults
  key: 1234567890ABCDEF1234567890ABCDEF
  iv: 1234567890ABCDEF
  cipher: aes-128-cbc

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEArLx40EqX3abkiHMnVQjMcfO18bbVjiegI83s6xa8RJIfUI+E
    fiBaerBYgT1NH4eVoQEcXxXqdIEIzAdsYqQ+w7BeIBp7/rl78tzPBtzE7tAkedX2
    ms9W8vOOIJyCC/tB1/vF+6rByUvjXxnJeiyoqm9bb3FvPJ5kZxa7A2mQyUrVfU94
    SszPKW9pYMUc9qMO+dT6hIwA3Q0U1OGLCdEHJ1AGqF748/eW86jJL02dBItK8WUi
    5S/2GmsL7bsQCsdHCQmyqTYbxY2Rb1O9r3Ac4Lr6PU/a+w1M/trfr2NM2qE9lt/4
    dHrCRJkym1GHxsjiWCE6lEnEyed8+36VpiGytQIDAQABAoIBABY2CebmoI58xkgR
    Xo5dmkRQzSVumBk2WS4hbYRxIPZEP8iRG71IFbpO8KJ1qnQScBgK14YWgFZIvUPW
    9IXejr+E7yV7olQHr7tzzx8Xxi7bDsWn0JTpckm9LZpd5Y762OWX10ZcF5z1qB/z
    ZefS1EFOHli/IkmOKGTlFFkE+vwW8DBAnVBpMuoMkxL3CskuxwfwN1/BG1sDaOj2
    Zsa9TJhjQPN4PAaI8XLaNFyA+AaMA1urUEiJApGWlVir0LoAf6etRkjgdwD5obtm
    SKTJoKPDNcRavXcmxeGuDfmuK5lffdfn9FCTmHefnUF52qlbpMldUIPXOBEEbp7W
    qlJPhIUCgYEA2JYWgaMsg5Wl8LOQywTGMI3iNFdRLRjDYK4BR4fOvs6naBTDy2Or
    RQOVJ+sG7sYQDgLNaWSBip7S4K0Y0yuwQxoOcelxIDfbhyp4KBw7DYB0pfDCo/l9
    6ErsEaFcZY1aNpv2WCLdfw1Qcsr0hBS2NZK33GvnFAf+9TfY3YxYW9MCgYEAzCuU
    iaAbaNrMFIhSQCLYo8TzMJ++B2BRudoKCsltNHU4FkbF75kzMpAfE3+3hVbAr65x
    cvfguTvTQdisZwrbyaG7H/8WAX6MMoUESkt5rBZOumJZFzvCGBrTr/UsQrmLOHRn
    DXPqFqyiTxOOrd6ozR/BGs3GPmfKWFXKMuwCylcCgYA5QWwPt0A0ROJKQF39nXR7
    L3bmGVMnVc2IiFdkPn2kKWNN+3dLFD0ZkHnkxJfflVJ3Mbx1qREpwRTEOl4+rOT6
    yC+bY3f5aWrKT6rWB6iAyD2OBJif2nuzZeMEQiD346c+mnpEEGt3g+CJiCedpxAI
    F5ItXgUHYZm/35Sf9NMC6wKBgDDboPEKOmTuLvYe5Sfp7tPJ9rRFFdFoEEacUdjg
    +NwbzO8vwoAitii8amNdJcqnxvaDlSyA+ur40QYp1p/V7mCi7keq4FY9NUmFoVAy
    HYy7zd02WcGAkGL6UHwD/LJ++jzpRhvnCDai2zh3Iqai6NwlZC2I3o7igX6AESH8
    bnKDAoGBAJLPIBONTy+bLx6zh2yTSeu0j8S9Tsfi+5/fZvl8U1JE17QHZPBGxFwf
    oct6I83dRIPozergjzzP+DRkyUVtpEMEz6OAUWXwEZu04tCdfuuV3PhX3NQj2h/N
    7jbQQnMuZiH0/1sPHmo/KreoRHEGxg5DMv5gOCgdQSQG/e95Wzcg
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/just_neph_release.key
      iv_filename:  /etc/rails/keys/just_neph_release.iv
      cipher:       aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     base64strict

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAxK3QprO9K19tmtHg/WYFV0p5mWIJ6WuLtbSEXsJTaFI7pQ+j
    JokCb4l3dlPx7OxkFX5zCLXsAgoFPm0N5qXVb72AanUFN4NieNs4pKOqt4qk8aG2
    K0mSDDN44an6s5EzYnI4JxDR2ymBagBwE/uBu9iF2/3eJ9W/KBbjlMD/Os79wxqQ
    iqVFhZGfvD4bIJVhpNvCIUqkyUlNouDBzHNpqiVzEZv5RR496t3uhHD/y2XnmP/F
    hOQ8TjKHig1pI+bJ8PetOlP5Tuj7Wq0f7z3TUygvlIupDvPU+y+tSnAx8ElRW63b
    8iwxSCL97aGe6nlL32v2IIzd4vFUQU2h5GPNvwIDAQABAoIBAQCw2R3hl4LEqkUS
    zh+Bmqe4yuW2Lrp84dA5Lb1Mu21mQ3MQQ5RPRSkkg7YgdvD1OcXwscfcEEDLwJjg
    fgze1USq+fmrP9fWB9SWmYBAQk5yRT91ahQ0ri2dvPa36zDbH/fVUKD/N5eLerG8
    T/J3dVI9Rz9uBcMpjIAbGyG+EyAsjnc74OKwQv5hLzLEGRTUhIkjdF1Zko30yrLq
    fUDfLeDu0guTS5wBaCj/vwCQy1kXWOaHd27Vr1ZiNUo2pqEY9S1uXV5kaKI3wgOy
    ZtOGTbr8iym8N3XaOUlrcL66v6SpANjaDL9kad51hX/7BE4EiGQFzW3mFs9wNzIZ
    a8tUk75BAoGBAPmUL7VkuzDTfiDdIR+aA2D0Ny8THZEofP1jjbBGf8OqwT1xwwRC
    DGwdTn4Mpa2zCjVB2UEjpiHEyDrDGj9L24/7atxo1P0KWUBvRkFY6znotapqJU6V
    6ilhdhxyZSC+zQifhR0kcoBoE+ZYaZz6p8sFPo5HY6wCCQkElIkS/jzhAoGBAMm9
    NiW/Cl5a81OxcXS9VPR6fXbf78ydu4qvU4FyE/x6qJTPFewkG0rhgSvtBeuU7+m4
    Ba2LiprbqUfLaph4llo3iP+JddEAiwpwQjEOoDLbQvINNu1ncXAMAMILV6dg6LY/
    p+PH5PAmvC9dfXDhRJDnPQqxcE/GeXaIhFZr7b6fAoGBAKkWpY/+k/gLgYtgZZ2U
    aa+ZJX4GNGTxCmVdulPwH4WAPXWUimxrFyF0ZYZuqRzajRLx7u/76AU+3e0526GA
    klulGYwEljBtf3RxLyb8yDkumU3Apk/sr32jozK4qh0aR60M7lGFLPIkET9hLQSG
    qYGZpv0cDsItitOKP9vyez7hAoGAKMZDcXGhaNy9HYdZxRyXVSqEvUgZsaOXyjoR
    iLJD893ewOTyK15I3eOiNfycG7donjaBf0ga5Z3MIySsENEeonFjETL5Sxru/1cd
    Kcko+95xM3cUSPuFY/4pEQ810jC2GE/ZYSJ/1UIe+vvMZMpDD36NSeH/L0CQQDLr
    fIQn80UCgYEAlVhZm8nC79G/tJ2iWXJgMMQrwADFefaxmf9/Z6XhJG3XLW2iO879
    np2hMkwyCbDbY7HNpofNi9T7Ex0dIxMi+68u2e5aUKdAMDOlF1lAxshNRQvwDQ44
    0Su1VsYRyyp/Hf/JVOljJBH1DISkTjilNSAD/VhJIaCaRccz1YCcWZc=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/just_neph_production.key
      iv_filename:  /etc/rails/keys/just_neph_production.iv
      cipher:       aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     base64strict
